# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-05-07 16:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UerCourse',
            new_name='UserCourse',
        ),
    ]
